---
- name: "Check for domain_exporter binary"
  stat:
    path: "/usr/local/bin/domain_exporter"
  changed_when: false
  register: domain_exporter_install

- when: not domain_exporter_install.stat.exists
  block:
    - name: "Download domain_exporter..."
      get_url:
        url: '{{ domain_exporter_tgz_url }}'
        dest: /tmp/{{ domain_exporter_tgz }}
        timeout: 60
        mode: 0644

    - name: "Ensure install dir exists"
      file:
        path: '{{ domain_exporter_install_dir }}'
        state: directory
        mode: '0755'

    - name: "Unarchive domain_exporter..."
      unarchive:
        src: /tmp/{{ domain_exporter_tgz }}
        dest: '{{ domain_exporter_install_dir }}'
        remote_src: true
        mode: '0644'

    - name: "Copy domain_exporter binary..."
      copy:
        src: '{{ domain_exporter_install_dir }}/domain_exporter'
        dest: '/usr/local/bin/'
        remote_src: true
        mode: '0755'

- name: "Create symtemd for domain_exporter"
  template:
    src: domain_exporter.service
    dest: /lib/systemd/system/
    mode: '0644'
  notify: "restart domain_exporter"

- name: "Start domain_exporter.service"
  systemd:
    name: domain_exporter
    state: started
    enabled: true
    daemon_reload: true
